
on:
  push:
    branches: [master, devel]
  pull_request:
    branches: [master, devel]
  schedule:
    - cron '33 4 * * *'

name: check

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  NOT_CRAN: true
  WARNINGS_ARE_ERRORS: 1
  _R_CHECK_CRAN_INCOMING_REMOTE_: false
  _R_CHECK_TESTS_NLINES_: 0

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        action: [check]
        r: [release]
        include:
          - os: ubuntu-latest
            action: check
            r: devel
          - os: ubuntu-16.04
            action: check
            r: 3.5
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1 
        with:
          r-version: ${{ matrix.r }}
#      - uses: actions/cache@v2
#        with:
#          path: ${{ env.R_LIBS_USER }}
#          key: ${{ runner.os}}-${{ steps.install-r.outputs.instaled-r-version }}-${{ hashFiles('.github/r-depends.rds') }}
#          restore-keys: ${{ runner.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-
      - run: |
          ls -R
          set
