
on:
  push:
    branches: [master, devel]
  pull_request:
    branches: [master, devel]
  schedule:
    - cron: '33 4 * * *'  # work 4:33 in the morning
name: check

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  WARNINGS_ARE_ERRORS: 1
  _R_CHECK_CRAN_INCOMING_REMOTE_: false
  _R_CHECK_TESTS_NLINES_: 0  # disable limiting of output lines
  _R_CHECK_CRAN_INCOMING_: false

jobs:
  check:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # continue runs even when a parallel run failed
      matrix:
        # run on ubuntu, macos, windows. 20.04 is more recent than ubuntu-latest, currently.
        os: [macos-latest, windows-latest, ubuntu-20.04]
        action: [check]
        r: [release]
        include:
          # additionally run r-devel, but only on ubuntu, and an old R version on an old ubuntu
          - os: ubuntu-20.04
            action: check
            r: devel
          - os: ubuntu-16.04
            action: check
            r: 3.5

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1 
        id: install-r
        with:
          r-version: ${{ matrix.r }}
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Create Cache Key
        shell: Rscript {0}
        run: |
          if (!require("remotes", quietly = TRUE)) install.packages("remotes")
          writeLines(capture.output(print(remotes::dev_package_deps())), ".github/deps.txt")
      - uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.os }}-${{ steps.install-r.outputs.installed-r-version }}-${{ hashFiles('.github/deps.txt') }}
      - shell: Rscript {0}
        name: install necessary build env packages
        run: |
          if (!require("remotes", quietly = TRUE)) install.packages("remotes")
          if (!require("roxygen2", quietly = TRUE)) install.packages("roxygen2")
      - if: runner.os == 'Linux'
        name: install system requirements
        run: |
          while read -r depinst ; do
            echo "> $depinst"
            eval sudo $depinst
          done < <( Rscript -e "writeLines(remotes::system_requirements('ubuntu', '$( . /etc/os-release ; echo $VERSION_ID )'))")
      - shell: Rscript {0}
        name: install package dependencies
        run: | 
          remotes::install_deps(dependencies = TRUE)
      - name: Session Info
        shell: Rscript {0}
        run: |
          options(width = 200)
          installed.packages()[, c("Package", "Version", "Built")]
          sessionInfo() 
      - name: Document
        shell: Rscript {0}
        run: roxygen2::roxygenise()
      - name: Build
        working-directory: ..
        run: 'R CMD build */'
      - name: Check
        working-directory: ..
        run: 'R CMD check *.tar.gz'
      - name: Log
        if: ${{ failure() }}
        working-directory: ..
        run: 'cat *.Rcheck/00check.log'
      - name: Latex Log
        if: ${{ failure() }}
        working-directory: ..
        run: 'cat *.Rcheck/Rdlatex.log'

